version: '2'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    networks:
      - nettyNet
    mem_limit: 2g
    cpuset: "0"

  mongo:
    image: mongo:3
    mem_limit: 2g
    cpuset: "0"
    ports:
      - "27017:27017"   
    networks:
      - nettyNet

networks:
  nettyNet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.4.0/24
          ip_range: 10.0.4.0/24
          gateway: 10.0.4.1
